# Generated by Django 4.2.6 on 2024-01-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_district_remove_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nrc_back',
            field=models.ImageField(blank=True, null=True, upload_to='identity/'),
        ),
        migrations.AddField(
            model_name='user',
            name='nrc_front',
            field=models.ImageField(blank=True, null=True, upload_to='identity/'),
        ),
    ]
